version: '3'

services:

  swoole:
    build: swoole/
    volumes:
      - ../blog:/var/www
    ports:
      - "8080:5200"
    command: php ./bin/laravels start

  nginx:
    build: nginx/
    volumes:
      - ../blog:/var/www
      - ./nginx/sites:/etc/nginx/conf.d
    ports:
      - "8080:80"

  fpm:
    build: fpm/
    expose:
      - "9000"
    volumes:
      - ../blog:/var/www

  apache:
    build: apache
    volumes:
      - ../blog:/var/www/html
    ports:
      - "8080:80"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret